export const COUNTRIES_DATA: Record<string, string> = {
  "US": "United States", "CA": "Canada", "GB": "United Kingdom", "AR": "Argentina", "AU": "Australia", 
  "AT": "Austria", "BE": "Belgium", "BR": "Brazil", "CL": "Chile", "CN": "China", "CO": "Colombia", 
  "HR": "Croatia", "DK": "Denmark", "DO": "Dominican Republic", "EG": "Egypt", "FI": "Finland", 
  "FR": "France", "DE": "Germany", "GR": "Greece", "HK": "Hong Kong", "IN": "India", "ID": "Indonesia", 
  "IE": "Ireland", "IL": "Israel", "IT": "Italy", "JP": "Japan", "JO": "Jordan", "KW": "Kuwait", 
  "LB": "Lebanon", "MY": "Malaysia", "MX": "Mexico", "NL": "Netherlands", "NZ": "New Zealand", 
  "NG": "Nigeria", "NO": "Norway", "PK": "Pakistan", "PA": "Panama", "PE": "Peru", "PH": "Philippines", 
  "PL": "Poland", "RU": "Russia", "SA": "Saudi Arabia", "RS": "Serbia", "SG": "Singapore", 
  "ZA": "South Africa", "KR": "South Korea", "ES": "Spain", "SE": "Sweden", "CH": "Switzerland", 
  "TW": "Taiwan", "TH": "Thailand", "TR": "Turkey", "AE": "United Arab Emirates", "VE": "Venezuela", 
  "PT": "Portugal", "LU": "Luxembourg", "BG": "Bulgaria", "CZ": "Czech Republic", "SI": "Slovenia", 
  "IS": "Iceland", "SK": "Slovakia", "LT": "Lithuania", "TT": "Trinidad and Tobago", "BD": "Bangladesh", 
  "LK": "Sri Lanka", "KE": "Kenya", "HU": "Hungary", "MA": "Morocco", "CY": "Cyprus", "JM": "Jamaica", 
  "EC": "Ecuador", "RO": "Romania", "BO": "Bolivia", "GT": "Guatemala", "CR": "Costa Rica", "QA": "Qatar", 
  "SV": "El Salvador", "HN": "Honduras", "NI": "Nicaragua", "PY": "Paraguay", "UY": "Uruguay", 
  "PR": "Puerto Rico", "BA": "Bosnia and Herzegovina", "PS": "Palestine", "TN": "Tunisia", "BH": "Bahrain", 
  "VN": "Vietnam", "GH": "Ghana", "MU": "Mauritius", "UA": "Ukraine", "MT": "Malta", "BS": "The Bahamas", 
  "MV": "Maldives", "OM": "Oman", "MK": "North Macedonia", "LV": "Latvia", "EE": "Estonia", "IQ": "Iraq", 
  "DZ": "Algeria", "AL": "Albania", "NP": "Nepal", "MO": "Macau", "ME": "Montenegro", "SN": "Senegal", 
  "GE": "Georgia", "BN": "Brunei", "UG": "Uganda", "GP": "Guadeloupe", "BB": "Barbados", "AZ": "Azerbaijan", 
  "TZ": "Tanzania", "LY": "Libya", "MQ": "Martinique", "CM": "Cameroon", "BW": "Botswana", "ET": "Ethiopia", 
  "KZ": "Kazakhstan", "NA": "Namibia", "MG": "Madagascar", "NC": "New Caledonia", "MD": "Moldova", 
  "FJ": "Fiji", "BY": "Belarus", "JE": "Jersey", "GU": "Guam", "YE": "Yemen", "ZM": "Zambia", 
  "IM": "Isle Of Man", "HT": "Haiti", "KH": "Cambodia", "AW": "Aruba", "PF": "French Polynesia", 
  "AF": "Afghanistan", "BM": "Bermuda", "GY": "Guyana", "AM": "Armenia", "MW": "Malawi", "AG": "Antigua", 
  "RW": "Rwanda", "GG": "Guernsey", "GM": "The Gambia", "FO": "Faroe Islands", "LC": "St. Lucia", 
  "KY": "Cayman Islands", "BJ": "Benin", "AD": "Andorra", "GD": "Grenada", "VI": "US Virgin Islands", 
  "BZ": "Belize", "VC": "Saint Vincent and the Grenadines", "MN": "Mongolia", "MZ": "Mozambique", 
  "ML": "Mali", "AO": "Angola", "GF": "French Guiana", "UZ": "Uzbekistan", "DJ": "Djibouti", 
  "BF": "Burkina Faso", "MC": "Monaco", "TG": "Togo", "GL": "Greenland", "GA": "Gabon", "GI": "Gibraltar", 
  "CD": "Democratic Republic of the Congo", "KG": "Kyrgyzstan", "PG": "Papua New Guinea", "BT": "Bhutan", 
  "KN": "Saint Kitts and Nevis", "SZ": "Swaziland", "LS": "Lesotho", "LA": "Laos", "LI": "Liechtenstein", 
  "MP": "Northern Mariana Islands", "SR": "Suriname", "SC": "Seychelles", "VG": "British Virgin Islands", 
  "TC": "Turks and Caicos Islands", "DM": "Dominica", "MR": "Mauritania", "AX": "Aland Islands", 
  "SM": "San Marino", "SY": "Syria", "SL": "Sierra Leone", "NE": "Niger", "CG": "Republic of the Congo", 
  "AI": "Anguilla", "YT": "Mayotte", "CV": "Cape Verde", "GN": "Guinea", "TM": "Turkmenistan", 
  "BI": "Burundi", "TJ": "Tajikistan", "VU": "Vanuatu", "SB": "Solomon Islands", "ER": "Eritrea", 
  "WS": "Samoa", "AS": "American Samoa", "FK": "Falkland Islands", "GQ": "Equatorial Guinea", "TO": "Tonga", 
  "KM": "Comoros", "PW": "Palau", "FM": "Federated States of Micronesia", "CF": "Central African Republic", 
  "SO": "Somalia", "MH": "Marshall Islands", "VA": "Vatican City", "TD": "Chad", "KI": "Kiribati", 
  "ST": "Sao Tome and Principe", "TV": "Tuvalu", "NR": "Nauru", "RE": "Réunion", "LR": "Liberia", 
  "ZW": "Zimbabwe", "CI": "Côte d'Ivoire", "MM": "Myanmar", "AN": "Netherlands Antilles", "AQ": "Antarctica", 
  "BQ": "Bonaire, Sint Eustatius and Saba", "BV": "Bouvet Island", "IO": "British Indian Ocean Territory", 
  "CX": "Christmas Island", "CC": "Cocos (Keeling) Islands", "CK": "Cook Islands", "CW": "Curaçao", 
  "TF": "French Southern Territories", "GW": "Guinea-Bissau", "HM": "Heard Island and McDonald Islands", 
  "XK": "Kosovo", "MS": "Montserrat", "NU": "Niue", "NF": "Norfolk Island", "PN": "Pitcairn", 
  "BL": "Saint Barthélemy", "SH": "Saint Helena", "MF": "Saint Martin", "PM": "Saint Pierre and Miquelon", 
  "SX": "Sint Maarten", "GS": "South Georgia and the South Sandwich Islands", "SS": "South Sudan", 
  "SJ": "Svalbard and Jan Mayen", "TL": "Timor-Leste", "TK": "Tokelau", "UM": "United States Minor Outlying Islands", 
  "WF": "Wallis and Futuna", "EH": "Western Sahara"
};

// Popular countries for quick access
export const POPULAR_COUNTRIES = ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'AE', 'SA', 'IN', 'BR', 'MX', 'ES'];