"""create_campaign_model_and_link_to_ad

Revision ID: 014e83d13d0a
Revises: 31ab1628a920
Create Date: 2025-07-06 21:55:01.128553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '014e83d13d0a'
down_revision: Union[str, None] = '31ab1628a920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_ads_campaign_id'), 'ads', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'ads', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('ads', 'creatives')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('creatives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_index(op.f('ix_ads_campaign_id'), table_name='ads')
    op.drop_column('ads', 'campaign_id')
    # ### end Alembic commands ###
