"""add_versioning_to_analyses_and_generations

Revision ID: 39d84fe61192
Revises: c02d04062e22
Create Date: 2025-11-16 17:41:49.202019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39d84fe61192'
down_revision: Union[str, None] = 'c02d04062e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_analyses', sa.Column('is_current', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('ad_analyses', sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint('ad_analyses_ad_id_key', 'ad_analyses', type_='unique')
    op.create_index(op.f('ix_ad_analyses_ad_id'), 'ad_analyses', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_analyses_is_current'), 'ad_analyses', ['is_current'], unique=False)
    op.add_column('veo_generations', sa.Column('prompt_hash', sa.String(), nullable=True))
    op.add_column('veo_generations', sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('veo_generations', sa.Column('is_current', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_veo_generations_is_current'), 'veo_generations', ['is_current'], unique=False)
    op.create_index(op.f('ix_veo_generations_prompt_hash'), 'veo_generations', ['prompt_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veo_generations_prompt_hash'), table_name='veo_generations')
    op.drop_index(op.f('ix_veo_generations_is_current'), table_name='veo_generations')
    op.drop_column('veo_generations', 'is_current')
    op.drop_column('veo_generations', 'version_number')
    op.drop_column('veo_generations', 'prompt_hash')
    op.drop_index(op.f('ix_ad_analyses_is_current'), table_name='ad_analyses')
    op.drop_index(op.f('ix_ad_analyses_ad_id'), table_name='ad_analyses')
    op.create_unique_constraint('ad_analyses_ad_id_key', 'ad_analyses', ['ad_id'])
    op.drop_column('ad_analyses', 'version_number')
    op.drop_column('ad_analyses', 'is_current')
    op.create_table('favorite_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='favorite_items_ad_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['favorite_lists.id'], name='favorite_items_list_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_items_pkey'),
    sa.UniqueConstraint('list_id', 'ad_id', name='uq_list_ad')
    )
    op.create_index('ix_favorite_items_list_id', 'favorite_items', ['list_id'], unique=False)
    op.create_index('ix_favorite_items_id', 'favorite_items', ['id'], unique=False)
    op.create_index('ix_favorite_items_ad_id', 'favorite_items', ['ad_id'], unique=False)
    op.create_table('favorite_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite_lists_pkey')
    )
    op.create_index('ix_favorite_lists_user_id', 'favorite_lists', ['user_id'], unique=False)
    op.create_index('ix_favorite_lists_id', 'favorite_lists', ['id'], unique=False)
    # ### end Alembic commands ###
