"""add_veo_script_session_and_history_tables

Revision ID: 4f0fd34205ba
Revises: i9j0k1l2m3n4
Create Date: 2025-11-27 08:56:02.232819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0fd34205ba'
down_revision: Union[str, None] = 'i9j0k1l2m3n4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_items_ad_id', table_name='favorite_items')
    op.drop_index('ix_favorite_items_id', table_name='favorite_items')
    op.drop_index('ix_favorite_items_list_id', table_name='favorite_items')
    op.drop_table('favorite_items')
    op.drop_index('ix_download_history_ad_archive_id', table_name='download_history')
    op.drop_index('ix_download_history_ad_id', table_name='download_history')
    op.drop_index('ix_download_history_created_at', table_name='download_history')
    op.drop_index('ix_download_history_id', table_name='download_history')
    op.drop_table('download_history')
    op.drop_index('ix_favorite_lists_id', table_name='favorite_lists')
    op.drop_index('ix_favorite_lists_user_id', table_name='favorite_lists')
    op.drop_table('favorite_lists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_lists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('favorite_lists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorite_lists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_favorite_lists_user_id', 'favorite_lists', ['user_id'], unique=False)
    op.create_index('ix_favorite_lists_id', 'favorite_lists', ['id'], unique=False)
    op.create_table('download_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ad_archive_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video_hd_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('video_sd_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('image_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('video_hd_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('video_sd_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('video_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('save_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='download_history_pkey')
    )
    op.create_index('ix_download_history_id', 'download_history', ['id'], unique=False)
    op.create_index('ix_download_history_created_at', 'download_history', ['created_at'], unique=False)
    op.create_index('ix_download_history_ad_id', 'download_history', ['ad_id'], unique=False)
    op.create_index('ix_download_history_ad_archive_id', 'download_history', ['ad_archive_id'], unique=False)
    op.create_table('favorite_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='favorite_items_ad_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['favorite_lists.id'], name='favorite_items_list_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_items_pkey'),
    sa.UniqueConstraint('list_id', 'ad_id', name='uq_list_ad')
    )
    op.create_index('ix_favorite_items_list_id', 'favorite_items', ['list_id'], unique=False)
    op.create_index('ix_favorite_items_id', 'favorite_items', ['id'], unique=False)
    op.create_index('ix_favorite_items_ad_id', 'favorite_items', ['ad_id'], unique=False)
    # ### end Alembic commands ###
