"""Add api_usage table for usage tracking

Revision ID: 4f1bc26260f3
Revises: c2fca7da9231
Create Date: 2025-11-19 15:07:26.923854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1bc26260f3'
down_revision: Union[str, None] = 'c2fca7da9231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create api_usage table for tracking API usage per model
    op.create_table('api_usage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('api_key_index', sa.Integer(), nullable=True),
        sa.Column('prompt_tokens', sa.Integer(), nullable=False),
        sa.Column('cached_tokens', sa.Integer(), nullable=False),
        sa.Column('completion_tokens', sa.Integer(), nullable=False),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
        sa.Column('request_type', sa.String(length=50), nullable=True),
        sa.Column('ad_id', sa.BigInteger(), nullable=True),
        sa.Column('raw_metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_id'), 'api_usage', ['id'], unique=False)
    op.create_index(op.f('ix_api_usage_model_name'), 'api_usage', ['model_name'], unique=False)
    op.create_index(op.f('ix_api_usage_provider'), 'api_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_api_usage_created_at'), 'api_usage', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop api_usage table
    op.drop_index(op.f('ix_api_usage_created_at'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_provider'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_model_name'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_id'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
