"""add_enhanced_extraction_fields_and_cleanup_legacy

Revision ID: 568f9fde44b0
Revises: a220f98e38c2
Create Date: 2025-07-06 14:33:53.996725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '568f9fde44b0'
down_revision: Union[str, None] = 'a220f98e38c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('campaign_id', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('meta_is_active', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('meta_cta_type', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('meta_display_format', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('meta_start_date', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('meta_end_date', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('targeting_data', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('lead_form_questions', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('lead_form_standalone_fields', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('creatives_data', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('advertiser_page_id', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('advertiser_page_name', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('advertiser_page_url', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('advertiser_page_likes', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('advertiser_page_profile_picture', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('platforms', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('is_enhanced_processed', sa.Boolean(), nullable=False))
    op.add_column('ads', sa.Column('enhanced_processing_version', sa.String(), nullable=True))
    op.drop_index('ix_ads_page_id', table_name='ads')
    op.create_index(op.f('ix_ads_advertiser_page_id'), 'ads', ['advertiser_page_id'], unique=False)
    op.create_index(op.f('ix_ads_campaign_id'), 'ads', ['campaign_id'], unique=False)
    op.drop_column('ads', 'start_date_readable')
    op.drop_column('ads', 'main_title')
    op.drop_column('ads', 'form_details')
    op.drop_column('ads', 'impressions_index')
    op.drop_column('ads', 'running_countries')
    op.drop_column('ads', 'page_like_count')
    op.drop_column('ads', 'end_date_readable')
    op.drop_column('ads', 'extra_texts')
    op.drop_column('ads', 'card_bodies')
    op.drop_column('ads', 'contains_digital_created_media')
    op.drop_column('ads', 'currency')
    op.drop_column('ads', 'card_urls')
    op.drop_column('ads', 'page_profile_uri')
    op.drop_column('ads', 'extra_links')
    op.drop_column('ads', 'card_titles')
    op.drop_column('ads', 'card_cta_texts')
    op.drop_column('ads', 'card_complete_data')
    op.drop_column('ads', 'main_body_text')
    op.drop_column('ads', 'main_caption')
    op.drop_column('ads', 'page_number')
    op.drop_column('ads', 'main_image_urls')
    op.drop_column('ads', 'page_categories')
    op.drop_column('ads', 'card_count')
    op.drop_column('ads', 'collation_count')
    op.drop_column('ads', 'card_media_types')
    op.drop_column('ads', 'main_video_urls')
    op.drop_column('ads', 'spend')
    op.drop_column('ads', 'structured_ad_copy')
    op.drop_column('ads', 'main_link_description')
    op.drop_column('ads', 'main_link_url')
    op.drop_column('ads', 'contains_sensitive_content')
    op.drop_column('ads', 'page_profile_picture_url')
    op.drop_column('ads', 'targeted_countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('targeted_countries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('page_profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('contains_sensitive_content', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_link_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_link_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('structured_ad_copy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('spend', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_video_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_media_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('collation_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('page_categories', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_image_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_caption', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_body_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_complete_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_cta_texts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_titles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('extra_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('page_profile_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('contains_digital_created_media', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('card_bodies', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('extra_texts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('end_date_readable', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('page_like_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('running_countries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('impressions_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('form_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('start_date_readable', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ads_campaign_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_advertiser_page_id'), table_name='ads')
    op.create_index('ix_ads_page_id', 'ads', ['page_id'], unique=False)
    op.drop_column('ads', 'enhanced_processing_version')
    op.drop_column('ads', 'is_enhanced_processed')
    op.drop_column('ads', 'platforms')
    op.drop_column('ads', 'advertiser_page_profile_picture')
    op.drop_column('ads', 'advertiser_page_likes')
    op.drop_column('ads', 'advertiser_page_url')
    op.drop_column('ads', 'advertiser_page_name')
    op.drop_column('ads', 'advertiser_page_id')
    op.drop_column('ads', 'creatives_data')
    op.drop_column('ads', 'lead_form_standalone_fields')
    op.drop_column('ads', 'lead_form_questions')
    op.drop_column('ads', 'targeting_data')
    op.drop_column('ads', 'meta_end_date')
    op.drop_column('ads', 'meta_start_date')
    op.drop_column('ads', 'meta_display_format')
    op.drop_column('ads', 'meta_cta_type')
    op.drop_column('ads', 'meta_is_active')
    op.drop_column('ads', 'campaign_id')
    # ### end Alembic commands ###
