"""enhanced_extraction_fields_and_cleanup

Revision ID: 5a527db67d43
Revises: 0a968eddd8d7
Create Date: 2025-07-06 17:19:37.862077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a527db67d43'
down_revision: Union[str, None] = '0a968eddd8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
