"""add_enhanced_extraction_fields_and_cleanup_legacy

Revision ID: 6168e4625f40
Revises: 568f9fde44b0
Create Date: 2025-07-06 14:39:39.986058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6168e4625f40'
down_revision: Union[str, None] = '568f9fde44b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
