"""Add comprehensive Facebook ads data fields

Revision ID: 779734a0c91c
Revises: 4b419cac5311
Create Date: 2025-07-03 16:52:23.691781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779734a0c91c'
down_revision: Union[str, None] = '4b419cac5311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('page_id', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('collation_id', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('collation_count', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ads', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('spend', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('impressions_index', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('display_format', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('page_like_count', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('page_categories', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('page_profile_uri', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('page_profile_picture_url', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('targeted_countries', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('contains_sensitive_content', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('contains_digital_created_media', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('main_title', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('main_body_text', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_caption', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_link_url', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('main_link_description', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_image_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('main_video_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_count', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('card_bodies', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_titles', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_cta_texts', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_media_types', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_complete_data', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('extra_texts', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('extra_links', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('start_date_readable', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('end_date_readable', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('page_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ads_page_id'), 'ads', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_page_id'), table_name='ads')
    op.drop_column('ads', 'page_number')
    op.drop_column('ads', 'end_date_readable')
    op.drop_column('ads', 'start_date_readable')
    op.drop_column('ads', 'extra_links')
    op.drop_column('ads', 'extra_texts')
    op.drop_column('ads', 'card_complete_data')
    op.drop_column('ads', 'card_media_types')
    op.drop_column('ads', 'card_urls')
    op.drop_column('ads', 'card_cta_texts')
    op.drop_column('ads', 'card_titles')
    op.drop_column('ads', 'card_bodies')
    op.drop_column('ads', 'card_count')
    op.drop_column('ads', 'main_video_urls')
    op.drop_column('ads', 'main_image_urls')
    op.drop_column('ads', 'main_link_description')
    op.drop_column('ads', 'main_link_url')
    op.drop_column('ads', 'main_caption')
    op.drop_column('ads', 'main_body_text')
    op.drop_column('ads', 'main_title')
    op.drop_column('ads', 'contains_digital_created_media')
    op.drop_column('ads', 'contains_sensitive_content')
    op.drop_column('ads', 'targeted_countries')
    op.drop_column('ads', 'page_profile_picture_url')
    op.drop_column('ads', 'page_profile_uri')
    op.drop_column('ads', 'page_categories')
    op.drop_column('ads', 'page_like_count')
    op.drop_column('ads', 'display_format')
    op.drop_column('ads', 'impressions_index')
    op.drop_column('ads', 'spend')
    op.drop_column('ads', 'currency')
    op.drop_column('ads', 'start_date')
    op.drop_column('ads', 'is_active')
    op.drop_column('ads', 'collation_count')
    op.drop_column('ads', 'collation_id')
    op.drop_column('ads', 'page_id')
    # ### end Alembic commands ###
