"""add_duration_days_to_ads

Revision ID: 8a69c9ce3517
Revises: 014e83d13d0a
Create Date: 2025-07-08 11:42:09.030863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a69c9ce3517'
down_revision: Union[str, None] = '014e83d13d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop foreign key constraint and campaign_id column
    op.drop_index('ix_ads_campaign_id', table_name='ads')
    op.drop_constraint('ads_campaign_id_fkey', 'ads', type_='foreignkey')
    op.drop_column('ads', 'campaign_id')
    
    # Then add the new duration_days column
    op.add_column('ads', sa.Column('duration_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ads_duration_days'), 'ads', ['duration_days'], unique=False)
    
    # Finally drop the campaigns table and its indexes
    op.drop_index('ix_campaigns_content_signature', table_name='campaigns')
    op.drop_index('ix_campaigns_id', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First recreate the campaigns table and its indexes
    op.create_table('campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_signature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creatives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey')
    )
    op.create_index('ix_campaigns_id', 'campaigns', ['id'], unique=False)
    op.create_index('ix_campaigns_content_signature', 'campaigns', ['content_signature'], unique=True)
    
    # Then remove duration_days column and index
    op.drop_index(op.f('ix_ads_duration_days'), table_name='ads')
    op.drop_column('ads', 'duration_days')
    
    # Finally add back campaign_id column and foreign key
    op.add_column('ads', sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_ads_campaign_id', 'ads', ['campaign_id'], unique=False)
    op.create_foreign_key('ads_campaign_id_fkey', 'ads', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
