"""add_form_details_running_countries_structured_ad_copy_to_ads

Revision ID: a220f98e38c2
Revises: 779734a0c91c
Create Date: 2025-07-04 13:44:11.317930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a220f98e38c2'
down_revision: Union[str, None] = '779734a0c91c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('form_details', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('running_countries', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('structured_ad_copy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'structured_ad_copy')
    op.drop_column('ads', 'running_countries')
    op.drop_column('ads', 'form_details')
    # ### end Alembic commands ###
