"""add_enhanced_extraction_fields_and_keep_legacy

Revision ID: a7031f8c7467
Revises: 6168e4625f40
Create Date: 2025-07-06 14:49:31.579960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7031f8c7467'
down_revision: Union[str, None] = '6168e4625f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
