"""add_enhanced_extraction_fields_hybrid_model

Revision ID: d26d6ee785d3
Revises: a7031f8c7467
Create Date: 2025-07-06 14:54:11.470819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26d6ee785d3'
down_revision: Union[str, None] = 'a7031f8c7467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('main_title', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_body_text', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_caption', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_link_url', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('main_link_description', sa.Text(), nullable=True))
    op.add_column('ads', sa.Column('main_image_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('main_video_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('page_like_count', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('page_categories', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('page_profile_uri', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('page_profile_picture_url', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('targeted_countries', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('impressions_index', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('spend', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('card_count', sa.Integer(), nullable=True))
    op.add_column('ads', sa.Column('card_titles', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_bodies', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_cta_texts', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_urls', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('card_complete_data', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('extra_texts', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('extra_links', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('form_details', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('running_countries', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('contains_sensitive_content', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('contains_digital_created_media', sa.Boolean(), nullable=True))
    op.add_column('ads', sa.Column('creatives', sa.JSON(), nullable=True))
    op.add_column('ads', sa.Column('extraction_version', sa.String(), nullable=True))
    op.add_column('ads', sa.Column('extraction_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('ads', 'collation_id')
    op.drop_column('ads', 'creatives_data')
    op.drop_column('ads', 'enhanced_processing_version')
    op.drop_column('ads', 'landing_page_url')
    op.drop_column('ads', 'is_enhanced_processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('is_enhanced_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('landing_page_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('enhanced_processing_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('creatives_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('collation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('ads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('ads', 'extraction_date')
    op.drop_column('ads', 'extraction_version')
    op.drop_column('ads', 'creatives')
    op.drop_column('ads', 'contains_digital_created_media')
    op.drop_column('ads', 'contains_sensitive_content')
    op.drop_column('ads', 'running_countries')
    op.drop_column('ads', 'form_details')
    op.drop_column('ads', 'extra_links')
    op.drop_column('ads', 'extra_texts')
    op.drop_column('ads', 'card_complete_data')
    op.drop_column('ads', 'card_urls')
    op.drop_column('ads', 'card_cta_texts')
    op.drop_column('ads', 'card_bodies')
    op.drop_column('ads', 'card_titles')
    op.drop_column('ads', 'card_count')
    op.drop_column('ads', 'currency')
    op.drop_column('ads', 'spend')
    op.drop_column('ads', 'impressions_index')
    op.drop_column('ads', 'targeted_countries')
    op.drop_column('ads', 'page_profile_picture_url')
    op.drop_column('ads', 'page_profile_uri')
    op.drop_column('ads', 'page_categories')
    op.drop_column('ads', 'page_like_count')
    op.drop_column('ads', 'main_video_urls')
    op.drop_column('ads', 'main_image_urls')
    op.drop_column('ads', 'main_link_description')
    op.drop_column('ads', 'main_link_url')
    op.drop_column('ads', 'main_caption')
    op.drop_column('ads', 'main_body_text')
    op.drop_column('ads', 'main_title')
    # ### end Alembic commands ###
