"""create_ad_sets_table_and_link_to_ads

Revision ID: e9be095c41d0
Revises: 8a69c9ce3517
Create Date: 2025-07-09 07:11:21.019365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9be095c41d0'
down_revision: Union[str, None] = '8a69c9ce3517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
